#!/bin/bash

SCRIPTDIR=$( (cd -P $(dirname $0) && pwd) )
corename=kanopy
DATADIR=${SCRIPTDIR}/data
BASEDIR=$( dirname $SCRIPTDIR )
COMMONDIR=${BASEDIR}/common


# load the shared bash functions log, vlog and Verbose
. $COMMONDIR/outputfuncs.bash $COMMONDIR

verbose=
force=
test=
while getopts :vfti: opt
 do
      case $opt in
          v) verbose=-v;;
          t) test=-t;;
          f) force=-f;;
      esac
done
shift $((OPTIND-1))

mkdir -p $DATADIR/incoming_zip
mkdir -p $DATADIR/processed_zip

date=`date "+%Y-%m-%d"`
kanopy_filename="Kanopy_MARC_Records__virginia.kanopystreaming.com__${date}.zip"
export PHANTOMJS_EXECUTABLE=$COMMONDIR/phantomjs
CASPERJS_PARMS="--web-security=no --verbose --log-level=info"

if [[ "$force" == "-f" && -e $DATADIR/incoming_zip/$kanopy_filename ]] ; then
    rm -f $DATADIR/incoming_zip/$kanopy_filename
fi

if [[ "$force" == "-f" && -e $DATADIR/processed_zip/$kanopy_filename ]] ; then
    rm -f $DATADIR/processed_zip/$kanopy_filename
fi

tries=0
done=0
if [[ ! -e $DATADIR/incoming_zip/$kanopy_filename && ! -e $DATADIR/processed_zip/$kanopy_filename ]] ; then
    while [[ "$done" == 0 && "$tries" < 3 ]]; do
        Verbose "    Running CasperJS to login and trigger download"
        timeout 5m $COMMONDIR/bin/casperjs $CASPERJS_PARMS $SCRIPTDIR/casper_kanopy.js virginia virginia235 $DATADIR/incoming_zip/$kanopy_filename > $DATADIR/casperjs_kanopy.log
        filesize=`du -b $DATADIR/incoming_zip/$kanopy_filename | cut -d $'\t' -f 1`
        Verbose "      Retrieved file size: $filesize"
        if [[ "$filesize" -lt 150000 ]]; then
            let tries=$tries+1
            if [[ $tries -lt 3 ]] ; then
                Verbose "      File size too small, trying again"
            else
                Verbose "      File size still too small giving up. Better luck tomorrow."
            fi
        else
            Verbose "    File size big enough, moving on."
            done=1
        fi
    done
else
    Verbose "    File $kanopy_filename already in incoming_zip directory or processed_zip directory"
fi


