#!/bin/bash

SCRIPTDIR=$( (cd -P $(dirname $0) && pwd) )
corename=swank
DATADIR=${SCRIPTDIR}/data
BASEDIR=$( dirname $SCRIPTDIR )
COMMONDIR=${BASEDIR}/common

# load the shared bash functions log, vlog and Verbose
. $COMMONDIR/outputfuncs.bash

marc4j_jar=$( find_newest_file_matching_pattern_under_directory $COMMONDIR "marc4j*.jar" )

DROPBOX_DIR=/lib_content30/Metadata_dropbox/swank/

verbose=
force=
test=
while getopts :vfti: opt
 do
      case $opt in
          v) verbose=-v;;
          t) test=-t;;
          f) force=-f;;
      esac
done
shift $((OPTIND-1))


DATE=`date "+%Y%m%d"`
export PHANTOMJS_EXECUTABLE=$COMMONDIR/kanopy2.5/phantomjs-2.5.0-beta-ubuntu-xenial/bin/phantomjs
CASPERJS_PARMS="--web-security=no --verbose --log-level=info"

if [[ "$force" == "-f" && -e $DATADIR/swank/swank_casper_${DATE}.csv ]] ; then
    rm -f $DATADIR/swank/swank_casper_${DATE}.csv
fi

if [[ "$force" == "-f" && -e $DATADIR/swank/swank_casper_${DATE}.mrc ]] ; then
    rm -f $DATADIR/swank/swank_casper_${DATE}.mrc
fi

 #$SCRIPTDIR/bin/casperjs --log-level=info --verbose --web-security=no casper_swank.js uva16 Admin001 data/swank/swank_casper_${DATE}.csv data/swank/swank_casper_${DATE}.mrc

tries=0
done=0
if [[ ! -e  $DATADIR/swank/swank_casper_${DATE}.csv || ! -e  $DATADIR/swank/swank_casper_${DATE}.mrc ]] ; then
    while [[ "$done" == 0 && "$tries" < 3 ]]; do
        Verbose "    Running CasperJS to login and trigger download"
        timeout 5m $COMMONDIR/bin/casperjs $CASPERJS_PARMS $SCRIPTDIR/casper_swank.js uva16 Admin001 $DATADIR/swank/swank_casper_${DATE}.csv $DATADIR/swank/swank_casper_${DATE}.mrc > $DATADIR/casperjs_swank.log
        filesize=`du -b $DATADIR/swank/swank_casper_${DATE}.mrc | cut -d $'\t' -f 1`
        Verbose "      Retrieved file size: $filesize"
        if [[ "$filesize" -lt 300000 ]]; then
            let tries=$tries+1
            if [[ $tries -lt 3 ]] ; then
                Verbose "      File size too small, trying again"
            else
                Verbose "      File size still too small giving up. Better luck tomorrow."
            fi
        else
            Verbose "    File size big enough, moving on."
            done=1
        fi
    done
else
    Verbose "    File  $DATADIR/swank/swank_casper_${DATE}.csv and  $DATADIR/swank/swank_casper_${DATE}.mrc already in swank data directory"
fi


